{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.interactions-hsg",
    "module": "losim",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-inprocess",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.36.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.android",
          "module": "annotations",
          "version": {
            "requires": "4.1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "losim-1.1.1.jar",
          "url": "losim-1.1.1.jar",
          "size": 365189,
          "sha512": "e37a9e39d3a89bf2e17b0af8af6222825719917fdd0838702ce93f798fcb04544959effd57d6a3ad68caa9b21770268ece9eb923a54c94644d8fd6cf7eb135bf",
          "sha256": "1ef008fa4c7199117cd920351fe2a1ad2977d988aa8ba562d5c3dbf39cdf71a8",
          "sha1": "c7a00f47e7e16b10124e1a16a7dac2f30ed0f6a2",
          "md5": "36c929021529c8152ff4051555ccf05b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-inprocess",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.36.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.android",
          "module": "annotations",
          "version": {
            "requires": "4.1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "losim-1.1.1.jar",
          "url": "losim-1.1.1.jar",
          "size": 365189,
          "sha512": "e37a9e39d3a89bf2e17b0af8af6222825719917fdd0838702ce93f798fcb04544959effd57d6a3ad68caa9b21770268ece9eb923a54c94644d8fd6cf7eb135bf",
          "sha256": "1ef008fa4c7199117cd920351fe2a1ad2977d988aa8ba562d5c3dbf39cdf71a8",
          "sha1": "c7a00f47e7e16b10124e1a16a7dac2f30ed0f6a2",
          "md5": "36c929021529c8152ff4051555ccf05b"
        }
      ]
    }
  ]
}
