{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.interactions-hsg",
    "module": "dissaly",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-inprocess",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.36.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.android",
          "module": "annotations",
          "version": {
            "requires": "4.1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "dissaly-4.0.0.jar",
          "url": "dissaly-4.0.0.jar",
          "size": 1057118,
          "sha512": "0dc3b4d9556345f8e4e081419fb6171b2f1537e79d538b38231e2aa098e79cfadadfcd74c4b0263f49ffdf56aef8aacbc0a7ddde2013216f061842308bac445a",
          "sha256": "8e98882f46fa750abbb34886fd31cb3c58bb474fc5446906691ecab7383e776f",
          "sha1": "9b89323783e070bf775a21697eb1b1c895fe1174",
          "md5": "e76c75d20a741f47e4e1633efc04afa0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-inprocess",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.36.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.android",
          "module": "annotations",
          "version": {
            "requires": "4.1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "dissaly-4.0.0.jar",
          "url": "dissaly-4.0.0.jar",
          "size": 1057118,
          "sha512": "0dc3b4d9556345f8e4e081419fb6171b2f1537e79d538b38231e2aa098e79cfadadfcd74c4b0263f49ffdf56aef8aacbc0a7ddde2013216f061842308bac445a",
          "sha256": "8e98882f46fa750abbb34886fd31cb3c58bb474fc5446906691ecab7383e776f",
          "sha1": "9b89323783e070bf775a21697eb1b1c895fe1174",
          "md5": "e76c75d20a741f47e4e1633efc04afa0"
        }
      ]
    }
  ]
}
