// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dissaly/job.proto
// Protobuf Java Version: 4.36.0

package dissaly.pb;

@com.google.protobuf.Generated
public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dissaly.Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; answer = 1;</code>
   */
  int getAnswerCount();
  /**
   * <code>map&lt;string, string&gt; answer = 1;</code>
   */
  boolean containsAnswer(
      java.lang.String key);
  /**
   * Use {@link #getAnswerMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAnswer();
  /**
   * <code>map&lt;string, string&gt; answer = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAnswerMap();
  /**
   * <code>map&lt;string, string&gt; answer = 1;</code>
   */
  /* nullable */
java.lang.String getAnswerOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; answer = 1;</code>
   */
  java.lang.String getAnswerOrThrow(
      java.lang.String key);
}
