// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dissaly/job.proto
// Protobuf Java Version: 4.36.0

package dissaly.pb;

@com.google.protobuf.Generated
public interface WorkloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dissaly.Workload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * How many units Load actually produced. Not necessarily Input.count: a Job
   * that drops malformed rows or folds duplicates produces fewer, and the trace
   * records both, because a Load that quietly returns a tenth of what it was
   * asked for is how a fitted exponent goes wrong for a reason nobody finds.
   * </pre>
   *
   * <code>int64 count = 1;</code>
   * @return The count.
   */
  long getCount();

  /**
   * <pre>
   * The work, as one of the system's own messages: its full name, and its bytes.
   *
   * Spelled out rather than google.protobuf.Any, which is the same two fields
   * under a name that promises more than dissaly can deliver. Unpacking an Any for
   * the trace needs a TypeRegistry, which lives in protobuf-java-util, which is
   * not vendored — so an Any would render as opaque bytes exactly like this does,
   * while making every assignment's protoc need the well-known types on an
   * include path. Two fields, no dependency, same capability.
   *
   * Load packs (off the clock) and Run parses (on it), which is the honest split:
   * reading your input is dissaly's cost, and unpacking it is your design's.
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * The work, as one of the system's own messages: its full name, and its bytes.
   *
   * Spelled out rather than google.protobuf.Any, which is the same two fields
   * under a name that promises more than dissaly can deliver. Unpacking an Any for
   * the trace needs a TypeRegistry, which lives in protobuf-java-util, which is
   * not vendored — so an Any would render as opaque bytes exactly like this does,
   * while making every assignment's protoc need the well-known types on an
   * include path. Two fields, no dependency, same capability.
   *
   * Load packs (off the clock) and Run parses (on it), which is the honest split:
   * reading your input is dissaly's cost, and unpacking it is your design's.
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>bytes payload = 3;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
