// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: losim/job.proto
// Protobuf Java Version: 4.36.0

package losim.pb;

@com.google.protobuf.Generated
public interface InputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:losim.Input)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A file or a directory, relative to the project root. Empty when the
   * scenario named none, which means Load generates from the seed instead.
   * </pre>
   *
   * <code>string source = 1;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <pre>
   * A file or a directory, relative to the project root. Empty when the
   * scenario named none, which means Load generates from the seed instead.
   * </pre>
   *
   * <code>string source = 1;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <pre>
   * What one item is, singular — "frame", "line", "order". The same word
   * Losim.current().units(n) counts and simulatedDuration's perUnit prices.
   * </pre>
   *
   * <code>string unit = 2;</code>
   * @return The unit.
   */
  java.lang.String getUnit();
  /**
   * <pre>
   * What one item is, singular — "frame", "line", "order". The same word
   * Losim.current().units(n) counts and simulatedDuration's perUnit prices.
   * </pre>
   *
   * <code>string unit = 2;</code>
   * @return The bytes for unit.
   */
  com.google.protobuf.ByteString
      getUnitBytes();

  /**
   * <pre>
   * How many of them this run is to process.
   * </pre>
   *
   * <code>int64 count = 3;</code>
   * @return The count.
   */
  long getCount();
}
