{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.interactions-hsg",
    "module": "losim",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-inprocess",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.36.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.android",
          "module": "annotations",
          "version": {
            "requires": "4.1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "losim-1.1.2.jar",
          "url": "losim-1.1.2.jar",
          "size": 366550,
          "sha512": "e55397cc1c44e1ad70b7196f494e0fc236e46ca2c334afc186baf72ea608c0eaed18841aba100452e90014968223232058a39001419f7e07e636af7b0885e640",
          "sha256": "de232bf09690ab302316fa78371582fff395e4661a89c10f2d797846c3c533c7",
          "sha1": "7034a298b281a71579598da68d21a5b7a8b39a30",
          "md5": "f188fa98f8ae3f41d730af64cf425c61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-inprocess",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.36.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.android",
          "module": "annotations",
          "version": {
            "requires": "4.1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "losim-1.1.2.jar",
          "url": "losim-1.1.2.jar",
          "size": 366550,
          "sha512": "e55397cc1c44e1ad70b7196f494e0fc236e46ca2c334afc186baf72ea608c0eaed18841aba100452e90014968223232058a39001419f7e07e636af7b0885e640",
          "sha256": "de232bf09690ab302316fa78371582fff395e4661a89c10f2d797846c3c533c7",
          "sha1": "7034a298b281a71579598da68d21a5b7a8b39a30",
          "md5": "f188fa98f8ae3f41d730af64cf425c61"
        }
      ]
    }
  ]
}
