// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dissaly/job.proto
// Protobuf Java Version: 4.36.0

package dissaly.pb;

/**
 * <pre>
 * What the simulation declared, already shrunk to the size this run is doing.
 *
 * `count` is the simulation's count times the fraction of it this run is measuring
 * — 1 for a direct run, and whichever rung the engine picked otherwise. Nothing
 * here says which: a Job that could tell a probe run from the full one could
 * behave differently at the two sizes, and then the projection would be a
 * projection of nothing.
 * </pre>
 *
 * Protobuf type {@code dissaly.Input}
 */
@com.google.protobuf.Generated
public final class Input extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:dissaly.Input)
    InputOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "Input");
  }
  // Use Input.newBuilder() to construct.
  private Input(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Input() {
    source_ = "";
    unit_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dissaly.pb.JobOuterClass.internal_static_dissaly_Input_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return dissaly.pb.JobOuterClass.internal_static_dissaly_Input_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dissaly.pb.JobOuterClass.internal_static_dissaly_Input_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dissaly.pb.Input.class, dissaly.pb.Input.Builder.class);
  }

  public static final int SOURCE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object source_ = "";
  /**
   * <pre>
   * A file or a directory, relative to the project root. Empty when the
   * simulation named none, which means Load generates from the seed instead.
   * </pre>
   *
   * <code>string source = 1;</code>
   * @return The source.
   */
  @java.lang.Override
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A file or a directory, relative to the project root. Empty when the
   * simulation named none, which means Load generates from the seed instead.
   * </pre>
   *
   * <code>string source = 1;</code>
   * @return The bytes for source.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNIT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object unit_ = "";
  /**
   * <pre>
   * What one item is, singular — "frame", "line", "order". The same word
   * Dissaly.current().units(n) counts and simulatedDuration's perUnit prices.
   * </pre>
   *
   * <code>string unit = 2;</code>
   * @return The unit.
   */
  @java.lang.Override
  public java.lang.String getUnit() {
    java.lang.Object ref = unit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unit_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * What one item is, singular — "frame", "line", "order". The same word
   * Dissaly.current().units(n) counts and simulatedDuration's perUnit prices.
   * </pre>
   *
   * <code>string unit = 2;</code>
   * @return The bytes for unit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnitBytes() {
    java.lang.Object ref = unit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNT_FIELD_NUMBER = 3;
  private long count_ = 0L;
  /**
   * <pre>
   * How many of them this run is to process.
   * </pre>
   *
   * <code>int64 count = 3;</code>
   * @return The count.
   */
  @java.lang.Override
  public long getCount() {
    return count_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unit_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, unit_);
    }
    if (count_ != 0L) {
      output.writeInt64(3, count_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unit_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, unit_);
    }
    if (count_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, count_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dissaly.pb.Input)) {
      return super.equals(obj);
    }
    dissaly.pb.Input other = (dissaly.pb.Input) obj;

    if (!getSource()
        .equals(other.getSource())) return false;
    if (!getUnit()
        .equals(other.getUnit())) return false;
    if (getCount()
        != other.getCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (37 * hash) + UNIT_FIELD_NUMBER;
    hash = (53 * hash) + getUnit().hashCode();
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCount());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dissaly.pb.Input parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dissaly.pb.Input parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dissaly.pb.Input parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dissaly.pb.Input parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dissaly.pb.Input parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dissaly.pb.Input parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dissaly.pb.Input parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dissaly.pb.Input parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dissaly.pb.Input parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dissaly.pb.Input parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dissaly.pb.Input parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dissaly.pb.Input parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dissaly.pb.Input prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * What the simulation declared, already shrunk to the size this run is doing.
   *
   * `count` is the simulation's count times the fraction of it this run is measuring
   * — 1 for a direct run, and whichever rung the engine picked otherwise. Nothing
   * here says which: a Job that could tell a probe run from the full one could
   * behave differently at the two sizes, and then the projection would be a
   * projection of nothing.
   * </pre>
   *
   * Protobuf type {@code dissaly.Input}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dissaly.Input)
      dissaly.pb.InputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dissaly.pb.JobOuterClass.internal_static_dissaly_Input_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dissaly.pb.JobOuterClass.internal_static_dissaly_Input_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dissaly.pb.Input.class, dissaly.pb.Input.Builder.class);
    }

    // Construct using dissaly.pb.Input.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      source_ = "";
      unit_ = "";
      count_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dissaly.pb.JobOuterClass.internal_static_dissaly_Input_descriptor;
    }

    @java.lang.Override
    public dissaly.pb.Input getDefaultInstanceForType() {
      return dissaly.pb.Input.getDefaultInstance();
    }

    @java.lang.Override
    public dissaly.pb.Input build() {
      dissaly.pb.Input result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dissaly.pb.Input buildPartial() {
      dissaly.pb.Input result = new dissaly.pb.Input(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dissaly.pb.Input result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.source_ = source_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.unit_ = unit_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.count_ = count_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dissaly.pb.Input) {
        return mergeFrom((dissaly.pb.Input)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dissaly.pb.Input other) {
      if (other == dissaly.pb.Input.getDefaultInstance()) return this;
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getUnit().isEmpty()) {
        unit_ = other.unit_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getCount() != 0L) {
        setCount(other.getCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              source_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              unit_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              count_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object source_ = "";
    /**
     * <pre>
     * A file or a directory, relative to the project root. Empty when the
     * simulation named none, which means Load generates from the seed instead.
     * </pre>
     *
     * <code>string source = 1;</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A file or a directory, relative to the project root. Empty when the
     * simulation named none, which means Load generates from the seed instead.
     * </pre>
     *
     * <code>string source = 1;</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A file or a directory, relative to the project root. Empty when the
     * simulation named none, which means Load generates from the seed instead.
     * </pre>
     *
     * <code>string source = 1;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      source_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A file or a directory, relative to the project root. Empty when the
     * simulation named none, which means Load generates from the seed instead.
     * </pre>
     *
     * <code>string source = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      source_ = getDefaultInstance().getSource();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A file or a directory, relative to the project root. Empty when the
     * simulation named none, which means Load generates from the seed instead.
     * </pre>
     *
     * <code>string source = 1;</code>
     * @param value The bytes for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      source_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object unit_ = "";
    /**
     * <pre>
     * What one item is, singular — "frame", "line", "order". The same word
     * Dissaly.current().units(n) counts and simulatedDuration's perUnit prices.
     * </pre>
     *
     * <code>string unit = 2;</code>
     * @return The unit.
     */
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * What one item is, singular — "frame", "line", "order". The same word
     * Dissaly.current().units(n) counts and simulatedDuration's perUnit prices.
     * </pre>
     *
     * <code>string unit = 2;</code>
     * @return The bytes for unit.
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * What one item is, singular — "frame", "line", "order". The same word
     * Dissaly.current().units(n) counts and simulatedDuration's perUnit prices.
     * </pre>
     *
     * <code>string unit = 2;</code>
     * @param value The unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnit(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      unit_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * What one item is, singular — "frame", "line", "order". The same word
     * Dissaly.current().units(n) counts and simulatedDuration's perUnit prices.
     * </pre>
     *
     * <code>string unit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnit() {
      unit_ = getDefaultInstance().getUnit();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * What one item is, singular — "frame", "line", "order". The same word
     * Dissaly.current().units(n) counts and simulatedDuration's perUnit prices.
     * </pre>
     *
     * <code>string unit = 2;</code>
     * @param value The bytes for unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnitBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      unit_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long count_ ;
    /**
     * <pre>
     * How many of them this run is to process.
     * </pre>
     *
     * <code>int64 count = 3;</code>
     * @return The count.
     */
    @java.lang.Override
    public long getCount() {
      return count_;
    }
    /**
     * <pre>
     * How many of them this run is to process.
     * </pre>
     *
     * <code>int64 count = 3;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(long value) {

      count_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How many of them this run is to process.
     * </pre>
     *
     * <code>int64 count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      count_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dissaly.Input)
  }

  // @@protoc_insertion_point(class_scope:dissaly.Input)
  private static final dissaly.pb.Input DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dissaly.pb.Input();
  }

  public static dissaly.pb.Input getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Input>
      PARSER = new com.google.protobuf.AbstractParser<Input>() {
    @java.lang.Override
    public Input parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Input> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Input> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dissaly.pb.Input getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

