// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dissaly/job.proto
// Protobuf Java Version: 4.36.0

package dissaly.pb;

@com.google.protobuf.Generated
public final class JobOuterClass extends com.google.protobuf.GeneratedFile {
  private JobOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "JobOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dissaly_Input_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dissaly_Input_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dissaly_Workload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dissaly_Workload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dissaly_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dissaly_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dissaly_Result_AnswerEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dissaly_Result_AnswerEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021dissaly/job.proto\022\007dissaly\"4\n\005Input\022\016\n" +
      "\006source\030\001 \001(\t\022\014\n\004unit\030\002 \001(\t\022\r\n\005count\030\003 \001" +
      "(\003\"8\n\010Workload\022\r\n\005count\030\001 \001(\003\022\014\n\004type\030\002 " +
      "\001(\t\022\017\n\007payload\030\003 \001(\014\"d\n\006Result\022+\n\006answer" +
      "\030\001 \003(\0132\033.dissaly.Result.AnswerEntry\032-\n\013A" +
      "nswerEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002" +
      "8\0012`\n\003Job\022.\n\004Load\022\016.dissaly.Input\032\021.diss" +
      "aly.Workload\"\003\220\002\001\022)\n\003Run\022\021.dissaly.Workl" +
      "oad\032\017.dissaly.ResultB\016\n\ndissaly.pbP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dissaly_Input_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_dissaly_Input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dissaly_Input_descriptor,
        new java.lang.String[] { "Source", "Unit", "Count", });
    internal_static_dissaly_Workload_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_dissaly_Workload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dissaly_Workload_descriptor,
        new java.lang.String[] { "Count", "Type", "Payload", });
    internal_static_dissaly_Result_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_dissaly_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dissaly_Result_descriptor,
        new java.lang.String[] { "Answer", });
    internal_static_dissaly_Result_AnswerEntry_descriptor =
      internal_static_dissaly_Result_descriptor.getNestedType(0);
    internal_static_dissaly_Result_AnswerEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dissaly_Result_AnswerEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
