/**
 * Generated from {@code losim/proto/dissaly/job.proto}, and committed.
 *
 * <p>Regenerate with {@code bin/losim dev proto}. Nothing here is edited by hand;
 * a change belongs in the {@code .proto} and the verb writes the rest.
 *
 * <p><b>Why it is committed rather than generated by the build.</b> protoc is
 * vendored for two platforms, so a build that ran it could not run anywhere else,
 * and losim would stop being buildable on a machine nobody vendored a compiler
 * for. The same reasoning as {@code build.gradle.kts}'s refusal to reproduce the
 * test suite's protobuf.
 *
 * <p><b>Why an assignment must not generate its own copy.</b> It would not crash,
 * and that is the problem. Every classloader losim builds delegates to its parent
 * first, so the jar's copy wins and the project's is compiled, shipped and never
 * loaded — a duplicate that costs a protoc run and a javac run to produce and says
 * nothing while it exists. What it does break is everything that counts schemas
 * rather than loads them: {@code losim check} reports rpcs nobody wrote, and the
 * project's output directory contains classes claiming to be losim's. So an
 * assignment's protoc gets {@code dissaly/job.proto} on its include path and never as
 * an input file.
 */
package dissaly.pb;
