{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.interactions-hsg",
    "module": "losim",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-inprocess",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.36.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.android",
          "module": "annotations",
          "version": {
            "requires": "4.1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "losim-1.5.0.jar",
          "url": "losim-1.5.0.jar",
          "size": 972398,
          "sha512": "8b569d42b071a2a86d499a85b82be0a5088bb3a8540ff7509433f79831bc1f2ab69067dd2dba784036d228c0b8a39ce75b53889850940522c17a37a09e67e444",
          "sha256": "d2c19ef8fb1c2f40930f6fbc7811dde97f8ec05107bafdc7b78e43a22986338e",
          "sha1": "ab31be81d25be0c4dee83251f545d16360927143",
          "md5": "5e28c3dc2fb3daa39f8bbcf15d257dab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-inprocess",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.83.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.36.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.android",
          "module": "annotations",
          "version": {
            "requires": "4.1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "losim-1.5.0.jar",
          "url": "losim-1.5.0.jar",
          "size": 972398,
          "sha512": "8b569d42b071a2a86d499a85b82be0a5088bb3a8540ff7509433f79831bc1f2ab69067dd2dba784036d228c0b8a39ce75b53889850940522c17a37a09e67e444",
          "sha256": "d2c19ef8fb1c2f40930f6fbc7811dde97f8ec05107bafdc7b78e43a22986338e",
          "sha1": "ab31be81d25be0c4dee83251f545d16360927143",
          "md5": "5e28c3dc2fb3daa39f8bbcf15d257dab"
        }
      ]
    }
  ]
}
